<section class="cxx entity class">
<h1 id="Arcadia_ADL_SampleBufferDefinition">Arcadia_ADL_SampleBufferDefinition</h1>
<my-signature><code>
Arcadia_ADL_SampleBufferDefinition
</code></my-signature>

<my-summary>
The definition of a sample buffer: a digital signal of a given duration generated by a digital signal processing (DSP) definition.
</my-summary>

<my-remarks>
<p>
The type name of the definition, used as the <code>type</code> entry of an ADL
asset, is <code>"SampleBuffer"</code>. The sample buffer holds a reference to the
DSP its signal is generated with, resolved when the definition is linked.
</p>
</my-remarks>

<section class="cxx methods">
<h1>Methods</h1>

<section class="cxx method">
<h1 id="Arcadia_ADL_SampleBufferDefinition_create">Arcadia_ADL_SampleBufferDefinition_create</h1>
<my-signature><code>
Arcadia_ADL_SampleBufferDefinition* Arcadia_ADL_SampleBufferDefinition_create
&nbsp;&nbsp;(Arcadia_Thread* thread,
&nbsp;&nbsp;&nbsp;Arcadia_ADL_Definitions* definitions,
&nbsp;&nbsp;&nbsp;Arcadia_String* name,
&nbsp;&nbsp;&nbsp;Arcadia_Natural32Value duration,
&nbsp;&nbsp;&nbsp;Arcadia_ADL_Reference* dsp)
</code></my-signature>

<my-summary>
Create the definition of a sample buffer.
</my-summary>

<section class="cxx parameters">
<h1>Parameters</h1>
<div>
  <div>thread</div>
  <div>The thread.</div>
</div>
<div>
  <div>definitions</div>
  <div>The container the definition belongs to.</div>
</div>
<div>
  <div>name</div>
  <div>The name of the definition.</div>
</div>
<div>
  <div>duration</div>
  <div>The duration, in seconds, of the sample buffer.</div>
</div>
<div>
  <div>dsp</div>
  <div>The reference to the DSP the sample buffer is generated with.</div>
</div>
</section>

<section class="cxx return-value">
<h1>Return value</h1>
The definition of the sample buffer.
</section>

<section class="cxx errors">
<h1>Errors</h1>
<div>Raises <code>Arcadia_Status_AllocationFailed</code> if the definition cannot be allocated.</div>
</section>
</section>

</section>

</section>